language : cpp

compiler :
  - gcc
  
before_install:
  - sudo apt-get update
  # Install and upgrade autoconf
  - sudo apt-get install autoconf
  - sudo add-apt-repository ppa:dns/gnu -y
  - sudo apt-get update -q
  - sudo apt-get install --only-upgrade autoconf
  # Upgrade gcc
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update; sudo apt-get install gcc-4.8 g++-4.8
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 60 --slave /usr/bin/g++ g++ /usr/bin/g++-4.8
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.6 40 --slave /usr/bin/g++ g++ /usr/bin/g++-4.6
  - gcc --version
  # Install dependencies
  - sudo apt-get install libgstreamer0.10-dev libudev-dev libglib2.0-dev libssl-dev libcrypto++-dev libcfitsio3-dev
  - sudo apt-get install libv4l-dev v4l-utils intltool gtk-doc-tools
  # Get opencv 2.4 at least
  - git submodule update --init --recursive
  - sudo add-apt-repository -y ppa:kubuntu-ppa/backports 
  - sudo apt-get update
  - sudo apt-get install libcv-dev libcvaux-dev libhighgui-dev libopencv-dev
  # Install newer boost compatible with gcc 4.8.
  - wget http://sourceforge.net/projects/boost/files/boost/1.55.0/boost_1_55_0.tar.bz2
  - tar -xvjf boost_1_55_0.tar.bz2 | tail -n 50
  - cd boost_1_55_0
  - sudo  ./bootstrap.sh --with-libraries="program_options,date_time,filesystem,system,iostreams,thread,log,chrono"
  - sudo ./b2 install | tail -n 50
  - cd ..
  # Get ARAVIS
  - wget https://github.com/AravisProject/aravis/archive/ARAVIS_0_3_7.tar.gz
  - tar -xvf ARAVIS_0_3_7.tar.gz
  - cd aravis-ARAVIS_0_3_7 && sh autogen.sh && ./configure 
  - sudo make install
  - cd ..
  
install :
  - sh bootstrap.sh
  
script :
  - ./configure
  - make
  
os : 
  - linux 
